export const COMPANIES = [
  {
    companyName: '시스템관리',
    companyCode: 'admin',
  },
  {
    companyName: '햇살카',
    companyCode: 'sunshine',
  },
  {
    companyName: '굿모닝카',
    companyCode: 'goodmorning',
  },
  {
    companyName: '행복카',
    companyCode: 'happy',
  },
  {
    companyName: '미래카',
    companyCode: 'future',
  },
  {
    companyName: '믿음카',
    companyCode: 'trust',
  },
  {
    companyName: '신뢰카',
    companyCode: 'reliable',
  },
  {
    companyName: '케이카',
    companyCode: 'kcar',
  },
  {
    companyName: '우리카',
    companyCode: 'ourcar',
  },
];

export const USERS = [
  {
    name: '시스템관리자',
    email: 'admin@dearcarmate.com',
    employeeNumber: '00001',
    phoneNumber: '010-0000-0000',
    password: 'admin1234',
    companyId: 1,
    isAdmin: true,
  },
  {
    name: '햇살카 대표',
    email: 'admin@sunshine.com',
    employeeNumber: '20001',
    phoneNumber: '010-2111-1111',
    password: 'password',
    companyId: 2,
  },
  {
    name: '햇살카 직원1',
    email: 'user1@sunshine.com',
    employeeNumber: '20002',
    phoneNumber: '010-2223-1112',
    password: 'password',
    companyId: 2,
  },
  {
    name: '햇살카 직원2',
    email: 'user2@sunshine.com',
    employeeNumber: '20003',
    phoneNumber: '010-2224-1113',
    password: 'password',
    companyId: 2,
  },
  {
    name: '햇살카 직원3',
    email: 'user3@sunshine.com',
    employeeNumber: '20004',
    phoneNumber: '010-2225-1114',
    password: 'password',
    companyId: 2,
  },
  {
    name: '햇살카 직원4',
    email: 'user4@sunshine.com',
    employeeNumber: '20005',
    phoneNumber: '010-2226-1115',
    password: 'password',
    companyId: 2,
  },
  {
    name: '햇살카 직원5',
    email: 'user5@sunshine.com',
    employeeNumber: '20006',
    phoneNumber: '010-2227-1116',
    password: 'password',
    companyId: 2,
  },
  {
    name: '햇살카 직원6',
    email: 'user6@sunshine.com',
    employeeNumber: '20007',
    phoneNumber: '010-2228-1117',
    password: 'password',
    companyId: 2,
  },
  {
    name: '햇살카 직원7',
    email: 'user7@sunshine.com',
    employeeNumber: '20008',
    phoneNumber: '010-2229-1118',
    password: 'password',
    companyId: 2,
  },
  {
    name: '햇살카 직원8',
    email: 'user8@sunshine.com',
    employeeNumber: '20009',
    phoneNumber: '010-2230-1119',
    password: 'password',
    companyId: 2,
  },
  {
    name: '굿모닝카 대표',
    email: 'admin@goodmorning.com',
    employeeNumber: '30001',
    phoneNumber: '010-3111-1111',
    password: 'password',
    companyId: 3,
  },
  {
    name: '굿모닝카 직원1',
    email: 'user1@goodmorning.com',
    employeeNumber: '30002',
    phoneNumber: '010-3223-1112',
    password: 'password',
    companyId: 3,
  },
  {
    name: '굿모닝카 직원2',
    email: 'user2@goodmorning.com',
    employeeNumber: '30003',
    phoneNumber: '010-3224-1113',
    password: 'password',
    companyId: 3,
  },
  {
    name: '굿모닝카 직원3',
    email: 'user3@goodmorning.com',
    employeeNumber: '30004',
    phoneNumber: '010-3225-1114',
    password: 'password',
    companyId: 3,
  },
  {
    name: '굿모닝카 직원4',
    email: 'user4@goodmorning.com',
    employeeNumber: '30005',
    phoneNumber: '010-3226-1115',
    password: 'password',
    companyId: 3,
  },
  {
    name: '굿모닝카 직원5',
    email: 'user5@goodmorning.com',
    employeeNumber: '30006',
    phoneNumber: '010-3227-1116',
    password: 'password',
    companyId: 3,
  },
  {
    name: '굿모닝카 직원6',
    email: 'user6@goodmorning.com',
    employeeNumber: '30007',
    phoneNumber: '010-3228-1117',
    password: 'password',
    companyId: 3,
  },
  {
    name: '굿모닝카 직원7',
    email: 'user7@goodmorning.com',
    employeeNumber: '30008',
    phoneNumber: '010-3229-1118',
    password: 'password',
    companyId: 3,
  },
  {
    name: '굿모닝카 직원8',
    email: 'user8@goodmorning.com',
    employeeNumber: '30009',
    phoneNumber: '010-3230-1119',
    password: 'password',
    companyId: 3,
  },
  {
    name: '행복카 대표',
    email: 'admin@happy.com',
    employeeNumber: '40001',
    phoneNumber: '010-4111-1111',
    password: 'password',
    companyId: 4,
  },
  {
    name: '행복카 직원1',
    email: 'user1@happy.com',
    employeeNumber: '40002',
    phoneNumber: '010-4223-1112',
    password: 'password',
    companyId: 4,
  },
  {
    name: '행복카 직원2',
    email: 'user2@happy.com',
    employeeNumber: '40003',
    phoneNumber: '010-4224-1113',
    password: 'password',
    companyId: 4,
  },
  {
    name: '행복카 직원3',
    email: 'user3@happy.com',
    employeeNumber: '40004',
    phoneNumber: '010-4225-1114',
    password: 'password',
    companyId: 4,
  },
  {
    name: '행복카 직원4',
    email: 'user4@happy.com',
    employeeNumber: '40005',
    phoneNumber: '010-4226-1115',
    password: 'password',
    companyId: 4,
  },
  {
    name: '행복카 직원5',
    email: 'user5@happy.com',
    employeeNumber: '40006',
    phoneNumber: '010-4227-1116',
    password: 'password',
    companyId: 4,
  },
  {
    name: '행복카 직원6',
    email: 'user6@happy.com',
    employeeNumber: '40007',
    phoneNumber: '010-4228-1117',
    password: 'password',
    companyId: 4,
  },
  {
    name: '행복카 직원7',
    email: 'user7@happy.com',
    employeeNumber: '40008',
    phoneNumber: '010-4229-1118',
    password: 'password',
    companyId: 4,
  },
  {
    name: '미래카 대표',
    email: 'admin@future.com',
    employeeNumber: '50001',
    phoneNumber: '010-5111-1111',
    password: 'password',
    companyId: 5,
  },

  {
    name: '미래카 직원1',
    email: 'user1@future.com',
    employeeNumber: '50002',
    phoneNumber: '010-5223-1112',
    password: 'password',
    companyId: 5,
  },
  {
    name: '미래카 직원2',
    email: 'user2@future.com',
    employeeNumber: '50003',
    phoneNumber: '010-5224-1113',
    password: 'password',
    companyId: 5,
  },
  {
    name: '미래카 직원3',
    email: 'user3@future.com',
    employeeNumber: '50004',
    phoneNumber: '010-5225-1114',
    password: 'password',
    companyId: 5,
  },
  {
    name: '미래카 직원4',
    email: 'user4@future.com',
    employeeNumber: '50005',
    phoneNumber: '010-5226-1115',
    password: 'password',
    companyId: 5,
  },
  {
    name: '미래카 직원5',
    email: 'user5@future.com',
    employeeNumber: '50006',
    phoneNumber: '010-5227-1116',
    password: 'password',
    companyId: 5,
  },
  {
    name: '미래카 직원6',
    email: 'user6@future.com',
    employeeNumber: '50007',
    phoneNumber: '010-5228-1117',
    password: 'password',
    companyId: 5,
  },
  {
    name: '미래카 직원7',
    email: 'user7@future.com',
    employeeNumber: '50008',
    phoneNumber: '010-5229-1118',
    password: 'password',
    companyId: 5,
  },
  {
    name: '믿음카 대표',
    email: 'admin@trust.com',
    employeeNumber: '60001',
    phoneNumber: '010-6111-1111',
    password: 'password',
    companyId: 6,
  },

  {
    name: '믿음카 직원1',
    email: 'user1@trust.com',
    employeeNumber: '60002',
    phoneNumber: '010-6223-1112',
    password: 'password',
    companyId: 6,
  },
  {
    name: '믿음카 직원2',
    email: 'user2@trust.com',
    employeeNumber: '60003',
    phoneNumber: '010-6224-1113',
    password: 'password',
    companyId: 6,
  },
  {
    name: '믿음카 직원3',
    email: 'user3@trust.com',
    employeeNumber: '60004',
    phoneNumber: '010-6225-1114',
    password: 'password',
    companyId: 6,
  },
  {
    name: '믿음카 직원4',
    email: 'user4@trust.com',
    employeeNumber: '60005',
    phoneNumber: '010-6226-1115',
    password: 'password',
    companyId: 6,
  },
  {
    name: '믿음카 직원5',
    email: 'user5@trust.com',
    employeeNumber: '60006',
    phoneNumber: '010-6227-1116',
    password: 'password',
    companyId: 6,
  },
  {
    name: '신뢰카 대표',
    email: 'admin@reliable.com',
    employeeNumber: '70001',
    phoneNumber: '010-7111-1111',
    password: 'password',
    companyId: 7,
  },
  {
    name: '신뢰카 직원1',
    email: 'user1@reliable.com',
    employeeNumber: '70002',
    phoneNumber: '010-7223-1112',
    password: 'password',
    companyId: 7,
  },
  {
    name: '신뢰카 직원2',
    email: 'user2@reliable.com',
    employeeNumber: '70003',
    phoneNumber: '010-7224-1113',
    password: 'password',
    companyId: 7,
  },
  {
    name: '신뢰카 직원3',
    email: 'user3@reliable.com',
    employeeNumber: '70004',
    phoneNumber: '010-7225-1114',
    password: 'password',
    companyId: 7,
  },

  {
    name: '신뢰카 직원4',
    email: 'user4@reliable.com',
    employeeNumber: '70005',
    phoneNumber: '010-7226-1115',
    password: 'password',
    companyId: 7,
  },

  {
    name: '신뢰카 직원5',
    email: 'user5@reliable.com',
    employeeNumber: '70006',
    phoneNumber: '010-7227-1116',
    password: 'password',
    companyId: 7,
  },

  {
    name: '신뢰카 직원6',
    email: 'user6@reliable.com',
    employeeNumber: '70007',
    phoneNumber: '010-7228-1117',
    password: 'password',
    companyId: 7,
  },

  {
    name: '신뢰카 직원7',
    email: 'user7@reliable.com',
    employeeNumber: '70008',
    phoneNumber: '010-7229-1118',
    password: 'password',
    companyId: 7,
  },
  {
    name: '신뢰카 직원8',
    email: 'user8@reliable.com',
    employeeNumber: '70009',
    phoneNumber: '010-7230-1119',
    password: 'password',
    companyId: 7,
  },
  {
    name: '우리카 대표',
    email: 'admin@ourcar.com',
    employeeNumber: '90001',
    phoneNumber: '010-9111-1111',
    password: 'password',
    companyId: 9,
  },
  {
    name: '우리카 직원1',
    email: 'user1@ourcar.com',
    employeeNumber: '90002',
    phoneNumber: '010-9223-1112',
    password: 'password',
    companyId: 9,
  },
  {
    name: '우리카 직원2',
    email: 'user2@ourcar.com',
    employeeNumber: '90003',
    phoneNumber: '010-9224-1113',
    password: 'password',
    companyId: 9,
  },
  {
    name: '우리카 직원3',
    email: 'user3@ourcar.com',
    employeeNumber: '90004',
    phoneNumber: '010-9225-1114',
    password: 'password',
    companyId: 9,
  },
  {
    name: '우리카 직원4',
    email: 'user4@ourcar.com',
    employeeNumber: '90005',
    phoneNumber: '010-9226-1115',
    password: 'password',
    companyId: 9,
  },
  {
    name: '우리카 직원5',
    email: 'user5@ourcar.com',
    employeeNumber: '90006',
    phoneNumber: '010-9227-1116',
    password: 'password',
    companyId: 9,
  },
  {
    name: '우리카 직원6',
    email: 'user6@ourcar.com',
    employeeNumber: '90007',
    phoneNumber: '010-9228-1117',
    password: 'password',
    companyId: 9,
  },
];

export const CUSTOMERS = [
  {
    name: '윤현진',
    gender: 'female',
    phoneNumber: '010-3333-4444',
    ageGroup: 'FIFTY',
    region: 'INCHEON',
    email: 'customer1@email.com',
    companyId: 2,
  },
  {
    name: '황현우',
    gender: 'male',
    phoneNumber: '010-3334-4445',
    ageGroup: 'TWENTY',
    region: 'DAEGU',
    email: 'customer2@email.com',
    companyId: 2,
  },
  {
    name: '전민수',
    gender: 'male',
    phoneNumber: '010-3335-4446',
    ageGroup: 'TWENTY',
    region: 'ULSAN',
    email: 'customer3@email.com',
    companyId: 2,
  },
  {
    name: '이동욱',
    gender: 'male',
    phoneNumber: '010-3336-4447',
    ageGroup: 'SIXTY',
    region: 'BUSAN',
    email: 'customer4@email.com',
    companyId: 2,
  },
  {
    name: '박수아',
    gender: 'female',
    phoneNumber: '010-3337-4448',
    ageGroup: 'SIXTY',
    region: 'GANGWON',
    email: 'customer5@email.com',
    companyId: 2,
  },
  {
    name: '조현진',
    gender: 'male',
    phoneNumber: '010-3338-4449',
    ageGroup: 'FIFTY',
    region: 'SEJONG',
    email: 'customer6@email.com',
    companyId: 2,
  },
  {
    name: '권성훈',
    gender: 'male',
    phoneNumber: '010-3339-4450',
    ageGroup: 'THIRTY',
    region: 'GYEONGNAM',
    email: 'customer7@email.com',
    companyId: 2,
  },
  {
    name: '송영희',
    gender: 'female',
    phoneNumber: '010-3340-4451',
    ageGroup: 'FORTY',
    region: 'GYEONGGI',
    email: 'customer8@email.com',
    companyId: 2,
  },
  {
    name: '전현우',
    gender: 'male',
    phoneNumber: '010-3341-4452',
    ageGroup: 'FIFTY',
    region: 'DAEGU',
    email: 'customer9@email.com',
    companyId: 2,
  },
  {
    name: '오영희',
    gender: 'female',
    phoneNumber: '010-3342-4453',
    ageGroup: 'TWENTY',
    region: 'DAEJEON',
    email: 'customer10@email.com',
    companyId: 2,
  },
  {
    name: '백준영',
    gender: 'male',
    phoneNumber: '010-3343-4455',
    ageGroup: 'THIRTY',
    region: 'SEJONG',
    email: 'customer11@email.com',
    companyId: 2,
  },
  {
    name: '백민수',
    gender: 'male',
    phoneNumber: '010-3344-4455',
    ageGroup: 'SIXTY',
    region: 'GYEONGNAM',
    email: 'customer12@email.com',
    companyId: 2,
  },
  {
    name: '안태민',
    gender: 'male',
    phoneNumber: '010-3345-4456',
    ageGroup: 'SIXTY',
    region: 'GYEONGNAM',
    email: 'customer13@email.com',
    companyId: 2,
  },
  {
    name: '박영희',
    gender: 'female',
    phoneNumber: '010-3346-4457',
    ageGroup: 'FORTY',
    region: 'CHUNGBUK',
    email: 'customer14@email.com',
    companyId: 2,
  },
  {
    name: '김지영',
    gender: 'female',
    phoneNumber: '010-3347-4458',
    ageGroup: 'SIXTY',
    region: 'SEOUL',
    email: 'customer15@email.com',
    companyId: 2,
  },
  {
    name: '백현진',
    gender: 'male',
    phoneNumber: '010-3368-4479',
    ageGroup: 'FORTY',
    region: 'INCHEON',
    email: 'customer36@email.com',
    companyId: 3,
  },
  {
    name: '최소연',
    gender: 'female',
    phoneNumber: '010-3369-4480',
    ageGroup: 'FIFTY',
    region: 'GWANGJU',
    email: 'customer37@email.com',
    companyId: 3,
  },
  {
    name: '송서연',
    gender: 'female',
    phoneNumber: '010-3370-4481',
    ageGroup: 'FORTY',
    region: 'GWANGJU',
    email: 'customer38@email.com',
    companyId: 3,
  },
  {
    name: '한현우',
    gender: 'male',
    phoneNumber: '010-3371-4482',
    ageGroup: 'THIRTY',
    region: 'GYEONGGI',
    email: 'customer39@email.com',
    companyId: 3,
  },
  {
    name: '한철수',
    gender: 'male',
    phoneNumber: '010-3372-4483',
    ageGroup: 'FORTY',
    region: 'GANGWON',
    email: 'customer40@email.com',
    companyId: 3,
  },
  {
    name: '윤예은',
    gender: 'female',
    phoneNumber: '010-3373-4484',
    ageGroup: 'FIFTY',
    region: 'JEONBUK',
    email: 'customer41@email.com',
    companyId: 3,
  },
  {
    name: '송예은',
    gender: 'female',
    phoneNumber: '010-3374-4485',
    ageGroup: 'TWENTY',
    region: 'SEJONG',
    email: 'customer42@email.com',
    companyId: 3,
  },
  {
    name: '고동욱',
    gender: 'male',
    phoneNumber: '010-3375-4486',
    ageGroup: 'FORTY',
    region: 'ULSAN',
    email: 'customer43@email.com',
    companyId: 3,
  },
  {
    name: '홍민준',
    gender: 'male',
    phoneNumber: '010-3376-4487',
    ageGroup: 'FORTY',
    region: 'JEONBUK',
    email: 'customer44@email.com',
    companyId: 3,
  },
  {
    name: '정태민',
    gender: 'male',
    phoneNumber: '010-3377-4488',
    ageGroup: 'TWENTY',
    region: 'DAEGU',
    email: 'customer45@email.com',
    companyId: 3,
  },
  {
    name: '황현우',
    gender: 'male',
    phoneNumber: '010-3378-4489',
    ageGroup: 'THIRTY',
    region: 'DAEJEON',
    email: 'customer46@email.com',
    companyId: 3,
  },
  {
    name: '윤서연',
    gender: 'female',
    phoneNumber: '010-3379-4490',
    ageGroup: 'FORTY',
    region: 'JEONBUK',
    email: 'customer47@email.com',
    companyId: 3,
  },
  {
    name: '한지명',
    gender: 'female',
    phoneNumber: '010-3380-4491',
    ageGroup: 'THIRTY',
    region: 'SEJONG',
    email: 'customer48@email.com',
    companyId: 3,
  },
  {
    name: '임민수',
    gender: 'male',
    phoneNumber: '010-3381-4492',
    ageGroup: 'FORTY',
    region: 'GANGWON',
    email: 'customer49@email.com',
    companyId: 3,
  },
  {
    name: '백수아',
    gender: 'female',
    phoneNumber: '010-3382-4493',
    ageGroup: 'SIXTY',
    region: 'GYEONGBUK',
    email: 'customer50@email.com',
    companyId: 3,
  },
  {
    name: '박철수',
    gender: 'male',
    phoneNumber: '010-3383-4494',
    ageGroup: 'FORTY',
    region: 'SEJONG',
    email: 'customer51@email.com',
    companyId: 3,
  },
  {
    name: '정민준',
    gender: 'male',
    phoneNumber: '010-3384-4495',
    ageGroup: 'FIFTY',
    region: 'JEONBUK',
    email: 'customer52@email.com',
    companyId: 3,
  },
  {
    name: '엄지원',
    gender: 'female',
    phoneNumber: '010-3385-4496',
    ageGroup: 'THIRTY',
    region: 'JEJU',
    email: 'customer53@email.com',
    companyId: 3,
  },
  {
    name: '전민준',
    gender: 'male',
    phoneNumber: '010-3386-4497',
    ageGroup: 'FORTY',
    region: 'GWANGJU',
    email: 'customer54@email.com',
    companyId: 4,
  },
  {
    name: '고지영',
    gender: 'female',
    phoneNumber: '010-3387-4498',
    ageGroup: 'THIRTY',
    region: 'JEONNAM',
    email: 'customer55@email.com',
    companyId: 4,
  },
  {
    name: '홍현진',
    gender: 'female',
    phoneNumber: '010-3388-4499',
    ageGroup: 'THIRTY',
    region: 'INCHEON',
    email: 'customer56@email.com',
    companyId: 4,
  },
  {
    name: '임현진',
    gender: 'male',
    phoneNumber: '010-3389-4500',
    ageGroup: 'THIRTY',
    region: 'GANGWON',
    email: 'customer57@email.com',
    companyId: 4,
  },
  {
    name: '황미영',
    gender: 'female',
    phoneNumber: '010-3390-4501',
    ageGroup: 'TWENTY',
    region: 'DAEGU',
    email: 'customer58@email.com',
    companyId: 4,
  },
  {
    name: '한민수',
    gender: 'male',
    phoneNumber: '010-3391-4502',
    ageGroup: 'FORTY',
    region: 'JEJU',
    email: 'customer59@email.com',
    companyId: 4,
  },
  {
    name: '김미영',
    gender: 'female',
    phoneNumber: '010-3392-4503',
    ageGroup: 'FIFTY',
    region: 'GYEONGBUK',
    email: 'customer60@email.com',
    companyId: 4,
  },
  {
    name: '오예은',
    gender: 'female',
    phoneNumber: '010-3393-4504',
    ageGroup: 'SIXTY',
    region: 'JEONNAM',
    email: 'customer61@email.com',
    companyId: 4,
  },
  {
    name: '전수아',
    gender: 'female',
    phoneNumber: '010-3394-4505',
    ageGroup: 'FIFTY',
    region: 'JEJU',
    email: 'customer62@email.com',
    companyId: 4,
  },
  {
    name: '이현진',
    gender: 'female',
    phoneNumber: '010-3395-4506',
    ageGroup: 'TWENTY',
    region: 'JEONBUK',
    email: 'customer63@email.com',
    companyId: 4,
  },
  {
    name: '전예은',
    gender: 'female',
    phoneNumber: '010-3396-4507',
    ageGroup: 'FORTY',
    region: 'GANGWON',
    email: 'customer64@email.com',
    companyId: 4,
  },
  {
    name: '유태민',
    gender: 'male',
    phoneNumber: '010-3397-4508',
    ageGroup: 'FORTY',
    region: 'JEJU',
    email: 'customer65@email.com',
    companyId: 4,
  },
  {
    name: '윤소연',
    gender: 'female',
    phoneNumber: '010-3398-4509',
    ageGroup: 'SIXTY',
    region: 'JEONBUK',
    email: 'customer66@email.com',
    companyId: 4,
  },
  {
    name: '한예은',
    gender: 'female',
    phoneNumber: '010-3399-4510',
    ageGroup: 'THIRTY',
    region: 'JEONBUK',
    email: 'customer67@email.com',
    companyId: 4,
  },
  {
    name: '최철수',
    gender: 'male',
    phoneNumber: '010-3400-4511',
    ageGroup: 'THIRTY',
    region: 'JEONBUK',
    email: 'customer68@email.com',
    companyId: 4,
  },
  {
    name: '윤미영',
    gender: 'female',
    phoneNumber: '010-3401-4512',
    ageGroup: 'FORTY',
    region: 'GWANGJU',
    email: 'customer69@email.com',
    companyId: 4,
  },
  {
    name: '박예은',
    gender: 'female',
    phoneNumber: '010-3402-4513',
    ageGroup: 'THIRTY',
    region: 'SEJONG',
    email: 'customer70@email.com',
    companyId: 4,
  },
  {
    name: '황영희',
    gender: 'female',
    phoneNumber: '010-3403-4514',
    ageGroup: 'TWENTY',
    region: 'JEJU',
    email: 'customer71@email.com',
    companyId: 4,
  },
  {
    name: '이민수',
    gender: 'male',
    phoneNumber: '010-3452-4563',
    ageGroup: 'FORTY',
    region: 'GYEONGNAM',
    email: 'customer120@email.com',
    companyId: 5,
  },
  {
    name: '이수아',
    gender: 'female',
    phoneNumber: '010-3453-4564',
    ageGroup: 'FIFTY',
    region: 'SEOUL',
    email: 'customer121@email.com',
    companyId: 5,
  },
  {
    name: '박민수',
    gender: 'male',
    phoneNumber: '010-3454-4565',
    ageGroup: 'FIFTY',
    region: 'CHUNGBUK',
    email: 'customer122@email.com',
    companyId: 5,
  },
  {
    name: '유민준',
    gender: 'male',
    phoneNumber: '010-3455-4566',
    ageGroup: 'FORTY',
    region: 'GWANGJU',
    email: 'customer123@email.com',
    companyId: 5,
  },
  {
    name: '김민준',
    gender: 'male',
    phoneNumber: '010-3456-4567',
    ageGroup: 'SIXTY',
    region: 'SEOUL',
    email: 'customer124@email.com',
    companyId: 5,
  },
  {
    name: '박민수',
    gender: 'male',
    phoneNumber: '010-3457-4568',
    ageGroup: 'THIRTY',
    region: 'JEJU',
    email: 'customer125@email.com',
    companyId: 5,
  },
  {
    name: '고지원',
    gender: 'male',
    phoneNumber: '010-3458-4569',
    ageGroup: 'FORTY',
    region: 'JEONBUK',
    email: 'customer126@email.com',
    companyId: 5,
  },
  {
    name: '황예은',
    gender: 'female',
    phoneNumber: '010-3459-4570',
    ageGroup: 'SIXTY',
    region: 'GYEONGBUK',
    email: 'customer127@email.com',
    companyId: 5,
  },
  {
    name: '임동욱',
    gender: 'male',
    phoneNumber: '010-3460-4571',
    ageGroup: 'FORTY',
    region: 'CHUNGNAM',
    email: 'customer128@email.com',
    companyId: 5,
  },
  {
    name: '백준영',
    gender: 'male',
    phoneNumber: '010-3461-4572',
    ageGroup: 'SIXTY',
    region: 'JEONNAM',
    email: 'customer129@email.com',
    companyId: 5,
  },
  {
    name: '이지훈',
    gender: 'male',
    phoneNumber: '010-3462-4573',
    ageGroup: 'TWENTY',
    region: 'SEJONG',
    email: 'customer130@email.com',
    companyId: 5,
  },
  {
    name: '홍지원',
    gender: 'male',
    phoneNumber: '010-3464-4575',
    ageGroup: 'FORTY',
    region: 'SEOUL',
    email: 'customer132@email.com',
    companyId: 5,
  },
  {
    name: '정태민',
    gender: 'male',
    phoneNumber: '010-3465-4576',
    ageGroup: 'FIFTY',
    region: 'GWANGJU',
    email: 'customer133@email.com',
    companyId: 5,
  },
  {
    name: '홍예은',
    gender: 'female',
    phoneNumber: '010-3466-4577',
    ageGroup: 'SIXTY',
    region: 'GWANGJU',
    email: 'customer134@email.com',
    companyId: 5,
  },
  {
    name: '강동욱',
    gender: 'male',
    phoneNumber: '010-3467-4578',
    ageGroup: 'SIXTY',
    region: 'GWANGJU',
    email: 'customer135@email.com',
    companyId: 5,
  },
  {
    name: '윤성훈',
    gender: 'male',
    phoneNumber: '010-3468-4579',
    ageGroup: 'SIXTY',
    region: 'GWANGJU',
    email: 'customer136@email.com',
    companyId: 5,
  },
  {
    name: '최준영',
    gender: 'male',
    phoneNumber: '010-3469-4580',
    ageGroup: 'SIXTY',
    region: 'CHUNGNAM',
    email: 'customer137@email.com',
    companyId: 5,
  },
  {
    name: '백수아',
    gender: 'female',
    phoneNumber: '010-3470-4581',
    ageGroup: 'SIXTY',
    region: 'GANGWON',
    email: 'customer138@email.com',
    companyId: 5,
  },
  {
    name: '이하은',
    gender: 'female',
    phoneNumber: '010-3471-4582',
    ageGroup: 'FORTY',
    region: 'GYEONGBUK',
    email: 'customer139@email.com',
    companyId: 5,
  },
  {
    name: '유성훈',
    gender: 'male',
    phoneNumber: '010-3472-4583',
    ageGroup: 'SIXTY',
    region: 'ULSAN',
    email: 'customer140@email.com',
    companyId: 5,
  },
  {
    name: '오민준',
    gender: 'male',
    phoneNumber: '010-3404-4515',
    ageGroup: 'TWENTY',
    region: 'JEJU',
    email: 'customer72@email.com',
    companyId: 6,
  },
  {
    name: '전하은',
    gender: 'female',
    phoneNumber: '010-3405-4516',
    ageGroup: 'SIXTY',
    region: 'ULSAN',
    email: 'customer73@email.com',
    companyId: 6,
  },
  {
    name: '박성훈',
    gender: 'male',
    phoneNumber: '010-3406-4517',
    ageGroup: 'FORTY',
    region: 'JEONBUK',
    email: 'customer74@email.com',
    companyId: 6,
  },
  {
    name: '김지훈',
    gender: 'male',
    phoneNumber: '010-3407-4518',
    ageGroup: 'SIXTY',
    region: 'JEONBUK',
    email: 'customer75@email.com',
    companyId: 6,
  },
  {
    name: '오지원',
    gender: 'female',
    phoneNumber: '010-3408-4519',
    ageGroup: 'SIXTY',
    region: 'GWANGJU',
    email: 'customer76@email.com',
    companyId: 6,
  },
  {
    name: '권영희',
    gender: 'female',
    phoneNumber: '010-3409-4520',
    ageGroup: 'THIRTY',
    region: 'SEOUL',
    email: 'customer77@email.com',
    companyId: 6,
  },
  {
    name: '박지영',
    gender: 'female',
    phoneNumber: '010-3410-4521',
    ageGroup: 'THIRTY',
    region: 'ULSAN',
    email: 'customer78@email.com',
    companyId: 6,
  },
  {
    name: '정성훈',
    gender: 'male',
    phoneNumber: '010-3411-4522',
    ageGroup: 'THIRTY',
    region: 'CHUNGNAM',
    email: 'customer79@email.com',
    companyId: 6,
  },
  {
    name: '황민준',
    gender: 'male',
    phoneNumber: '010-3412-4523',
    ageGroup: 'SIXTY',
    region: 'JEONBUK',
    email: 'customer80@email.com',
    companyId: 6,
  },
  {
    name: '한수아',
    gender: 'female',
    phoneNumber: '010-3413-4524',
    ageGroup: 'THIRTY',
    region: 'GYEONGGI',
    email: 'customer81@email.com',
    companyId: 6,
  },
  {
    name: '박미영',
    gender: 'female',
    phoneNumber: '010-3414-4525',
    ageGroup: 'SIXTY',
    region: 'BUSAN',
    email: 'customer82@email.com',
    companyId: 6,
  },
  {
    name: '김예은',
    gender: 'female',
    phoneNumber: '010-3415-4526',
    ageGroup: 'FORTY',
    region: 'INCHEON',
    email: 'customer83@email.com',
    companyId: 6,
  },
  {
    name: '전수아',
    gender: 'female',
    phoneNumber: '010-3416-4527',
    ageGroup: 'THIRTY',
    region: 'JEONNAM',
    email: 'customer84@email.com',
    companyId: 6,
  },
  {
    name: '전성훈',
    gender: 'male',
    phoneNumber: '010-3417-4528',
    ageGroup: 'FORTY',
    region: 'GWANGJU',
    email: 'customer85@email.com',
    companyId: 6,
  },
  {
    name: '박준호',
    gender: 'male',
    phoneNumber: '010-3418-4529',
    ageGroup: 'FIFTY',
    region: 'GWANGJU',
    email: 'customer86@email.com',
    companyId: 6,
  },
  {
    name: '전지훈',
    gender: 'male',
    phoneNumber: '010-3419-4530',
    ageGroup: 'TWENTY',
    region: 'CHUNGBUK',
    email: 'customer87@email.com',
    companyId: 6,
  },
  {
    name: '전준호',
    gender: 'male',
    phoneNumber: '010-3420-4531',
    ageGroup: 'FIFTY',
    region: 'JEJU',
    email: 'customer88@email.com',
    companyId: 7,
  },
  {
    name: '백명희',
    gender: 'female',
    phoneNumber: '010-3421-4532',
    ageGroup: 'FIFTY',
    region: 'JEJU',
    email: 'customer89@email.com',
    companyId: 7,
  },
  {
    name: '송예은',
    gender: 'female',
    phoneNumber: '010-3422-4533',
    ageGroup: 'SIXTY',
    region: 'GYEONGGI',
    email: 'customer90@email.com',
    companyId: 7,
  },
  {
    name: '백민수',
    gender: 'male',
    phoneNumber: '010-3423-4534',
    ageGroup: 'FIFTY',
    region: 'BUSAN',
    email: 'customer91@email.com',
    companyId: 7,
  },
  {
    name: '임민수',
    gender: 'male',
    phoneNumber: '010-3424-4535',
    ageGroup: 'FIFTY',
    region: 'JEJU',
    email: 'customer92@email.com',
    companyId: 7,
  },
  {
    name: '안철수',
    gender: 'male',
    phoneNumber: '010-3425-4536',
    ageGroup: 'FIFTY',
    region: 'JEONNAM',
    email: 'customer93@email.com',
    companyId: 7,
  },
  {
    name: '권지훈',
    gender: 'male',
    phoneNumber: '010-3426-4537',
    ageGroup: 'SIXTY',
    region: 'GYEONGNAM',
    email: 'customer94@email.com',
    companyId: 7,
  },
  {
    name: '권수아',
    gender: 'female',
    phoneNumber: '010-3427-4538',
    ageGroup: 'TWENTY',
    region: 'JEONNAM',
    email: 'customer95@email.com',
    companyId: 7,
  },
  {
    name: '권현우',
    gender: 'male',
    phoneNumber: '010-3428-4539',
    ageGroup: 'FIFTY',
    region: 'INCHEON',
    email: 'customer96@email.com',
    companyId: 7,
  },
  {
    name: '박동욱',
    gender: 'male',
    phoneNumber: '010-3429-4540',
    ageGroup: 'SIXTY',
    region: 'CHUNGNAM',
    email: 'customer97@email.com',
    companyId: 7,
  },
  {
    name: '권성훈',
    gender: 'male',
    phoneNumber: '010-3430-4541',
    ageGroup: 'FIFTY',
    region: 'GYEONGBUK',
    email: 'customer98@email.com',
    companyId: 7,
  },
  {
    name: '최철수',
    gender: 'male',
    phoneNumber: '010-3431-4542',
    ageGroup: 'FORTY',
    region: 'CHUNGBUK',
    email: 'customer99@email.com',
    companyId: 7,
  },
  {
    name: '백소연',
    gender: 'female',
    phoneNumber: '010-3432-4543',
    ageGroup: 'FORTY',
    region: 'ULSAN',
    email: 'customer100@email.com',
    companyId: 7,
  },
  {
    name: '강현우',
    gender: 'male',
    phoneNumber: '010-3433-4544',
    ageGroup: 'FORTY',
    region: 'SEOUL',
    email: 'customer101@email.com',
    companyId: 7,
  },
  {
    name: '고지훈',
    gender: 'male',
    phoneNumber: '010-3434-4545',
    ageGroup: 'TWENTY',
    region: 'SEJONG',
    email: 'customer102@email.com',
    companyId: 7,
  },
  {
    name: '권민수',
    gender: 'male',
    phoneNumber: '010-3435-4546',
    ageGroup: 'FIFTY',
    region: 'BUSAN',
    email: 'customer103@email.com',
    companyId: 7,
  },
  {
    name: '권하은',
    gender: 'female',
    phoneNumber: '010-3436-4547',
    ageGroup: 'TWENTY',
    region: 'DAEJEON',
    email: 'customer104@email.com',
    companyId: 9,
  },
  {
    name: '조동욱',
    gender: 'male',
    phoneNumber: '010-3437-4548',
    ageGroup: 'TWENTY',
    region: 'GYEONGGI',
    email: 'customer105@email.com',
    companyId: 9,
  },
  {
    name: '안서연',
    gender: 'female',
    phoneNumber: '010-3438-4549',
    ageGroup: 'TWENTY',
    region: 'GANGWON',
    email: 'customer106@email.com',
    companyId: 9,
  },
  {
    name: '정성훈',
    gender: 'male',
    phoneNumber: '010-3439-4550',
    ageGroup: 'TWENTY',
    region: 'JEONNAM',
    email: 'customer107@email.com',
    companyId: 9,
  },
  {
    name: '김영희',
    gender: 'female',
    phoneNumber: '010-3440-4551',
    ageGroup: 'FORTY',
    region: 'JEJU',
    email: 'customer108@email.com',
    companyId: 9,
  },
  {
    name: '권하은',
    gender: 'female',
    phoneNumber: '010-3441-4552',
    ageGroup: 'THIRTY',
    region: 'CHUNGNAM',
    email: 'customer109@email.com',
    companyId: 9,
  },
  {
    name: '박태민',
    gender: 'male',
    phoneNumber: '010-3442-4553',
    ageGroup: 'TWENTY',
    region: 'GWANGJU',
    email: 'customer110@email.com',
    companyId: 9,
  },
  {
    name: '한태민',
    gender: 'male',
    phoneNumber: '010-3443-4554',
    ageGroup: 'FIFTY',
    region: 'CHUNGBUK',
    email: 'customer111@email.com',
    companyId: 9,
  },
  {
    name: '고예은',
    gender: 'female',
    phoneNumber: '010-3444-4555',
    ageGroup: 'THIRTY',
    region: 'CHUNGNAM',
    email: 'customer112@email.com',
    companyId: 9,
  },
  {
    name: '안미영',
    gender: 'female',
    phoneNumber: '010-3445-4556',
    ageGroup: 'TWENTY',
    region: 'DAEGU',
    email: 'customer113@email.com',
    companyId: 9,
  },
  {
    name: '강현진',
    gender: 'female',
    phoneNumber: '010-3446-4557',
    ageGroup: 'FIFTY',
    region: 'GANGWON',
    email: 'customer114@email.com',
    companyId: 9,
  },
  {
    name: '이영희',
    gender: 'female',
    phoneNumber: '010-3447-4558',
    ageGroup: 'THIRTY',
    region: 'CHUNGBUK',
    email: 'customer115@email.com',
    companyId: 9,
  },
  {
    name: '오지훈',
    gender: 'male',
    phoneNumber: '010-3448-4559',
    ageGroup: 'THIRTY',
    region: 'SEOUL',
    email: 'customer116@email.com',
    companyId: 9,
  },
  {
    name: '박서연',
    gender: 'female',
    phoneNumber: '010-3449-4560',
    ageGroup: 'TWENTY',
    region: 'INCHEON',
    email: 'customer117@email.com',
    companyId: 9,
  },
  {
    name: '안준영',
    gender: 'male',
    phoneNumber: '010-3450-4561',
    ageGroup: 'THIRTY',
    region: 'JEONBUK',
    email: 'customer118@email.com',
    companyId: 9,
  },
  {
    name: '고미영',
    gender: 'female',
    phoneNumber: '010-3451-4562',
    ageGroup: 'SIXTY',
    region: 'GYEONGBUK',
    email: 'customer119@email.com',
    companyId: 9,
  },
];

export const CARS = [
  {
    carNumber: '15가1003',
    model: 'K3',
    manufacturingYear: 2023,
    mileage: 95834,
    price: 33098339,
    accidentCount: 0,
    status: 'contractProceeding',
    companyId: 2,
  },
  {
    carNumber: '17가1005',
    model: '모닝',
    manufacturingYear: 2023,
    mileage: 25381,
    price: 20857019,
    accidentCount: 0,
    status: 'contractProceeding',
    companyId: 2,
  },
  {
    carNumber: '22가1010',
    model: 'K3',
    manufacturingYear: 2020,
    mileage: 21514,
    price: 30080698,
    accidentCount: 0,
    status: 'contractProceeding',
    companyId: 2,
  },
  {
    carNumber: '20가1008',
    model: '아반떼',
    manufacturingYear: 2019,
    mileage: 86425,
    price: 0,
    accidentCount: 1,
    status: 'contractProceeding',
    companyId: 2,
  },
  {
    carNumber: '14가1002',
    model: 'K7',
    manufacturingYear: 2018,
    mileage: 86489,
    price: 37397586,
    accidentCount: 0,
    status: 'contractCompleted',
    companyId: 2,
  },
  {
    carNumber: '16가1004',
    model: 'K5',
    manufacturingYear: 2021,
    mileage: 71207,
    price: 53401189,
    accidentCount: 2,
    status: 'contractCompleted',
    companyId: 2,
  },
  {
    carNumber: '19가1007',
    model: '쏘렌토',
    manufacturingYear: 2019,
    mileage: 30697,
    price: 42066174,
    accidentCount: 0,
    status: 'contractProceeding',
    companyId: 2,
  },
  {
    carNumber: '18가1006',
    model: '스파크',
    manufacturingYear: 2019,
    mileage: 51436,
    price: 23992460,
    accidentCount: 2,
    status: 'contractProceeding',
    companyId: 2,
  },
  {
    carNumber: '12가1234',
    model: 'K3',
    manufacturingYear: 2025,
    mileage: 1,
    price: 1,
    accidentCount: 1,
    status: 'contractProceeding',
    companyId: 2,
  },
  {
    carNumber: '21가1009',
    model: '싼타페',
    manufacturingYear: 2019,
    mileage: 68432,
    price: 26669097,
    accidentCount: 0,
    status: 'contractProceeding',
    companyId: 2,
  },
  {
    carNumber: '12가1233',
    model: '그랜저',
    manufacturingYear: 2024,
    mileage: 1,
    price: 1,
    accidentCount: 1,
    status: 'contractProceeding',
    companyId: 2,
  },
  {
    carNumber: '12가1231',
    model: 'K5',
    manufacturingYear: 2025,
    mileage: 1,
    price: 1,
    accidentCount: 1,
    status: 'contractProceeding',
    companyId: 2,
  },
  {
    carNumber: '13가9234',
    model: 'K7',
    manufacturingYear: 2023,
    mileage: 1234,
    price: 2300000,
    accidentCount: 0,
    status: 'contractProceeding',
    companyId: 2,
  },
  {
    carNumber: '38가6157',
    model: '아반떼',
    manufacturingYear: 2023,
    mileage: 10000,
    price: 0,
    accidentCount: 0,
    status: 'possession',
    companyId: 2,
  },
  {
    carNumber: '23가1011',
    model: '그랜저',
    manufacturingYear: 2018,
    mileage: 40144,
    price: 28809075,
    accidentCount: 0,
    status: 'possession',
    companyId: 2,
  },
  {
    carNumber: '이것은테스트',
    model: '그랜저',
    manufacturingYear: 2024,
    mileage: 0,
    price: 0,
    accidentCount: 0,
    status: 'contractProceeding',
    companyId: 2,
  },
  {
    carNumber: '999하1234',
    model: '그랜저',
    manufacturingYear: 2023,
    mileage: 0,
    price: 0,
    accidentCount: 0,
    status: 'contractProceeding',
    companyId: 2,
  },
  {
    carNumber: '18가6477',
    model: '아반떼',
    manufacturingYear: 2025,
    mileage: 1000,
    price: 10000,
    accidentCount: 1,
    status: 'contractProceeding',
    companyId: 2,
  },
  {
    carNumber: '12가1000',
    model: '쏘렌토',
    manufacturingYear: 2021,
    mileage: 39907,
    price: 33046002,
    accidentCount: 0,
    status: 'contractCompleted',
    companyId: 2,
  },
];

export const CAR_MODELS = [
  {
    model: 'K3',
    manufacturer: '기아',
    type: 'SEDAN',
  },
  {
    model: 'K5',
    manufacturer: '기아',
    type: 'SEDAN',
  },
  {
    model: 'K7',
    manufacturer: '기아',
    type: 'SEDAN',
  },
  {
    model: '쏘렌토',
    manufacturer: '기아',
    type: 'SUV',
  },
  {
    model: '모닝',
    manufacturer: '기아',
    type: 'COMPACT',
  },
  {
    model: '아반떼',
    manufacturer: '현대',
    type: 'SEDAN',
  },
  {
    model: '그랜저',
    manufacturer: '현대',
    type: 'SEDAN',
  },
  {
    model: '싼타페',
    manufacturer: '현대',
    type: 'SUV',
  },
  {
    model: '스파크',
    manufacturer: '쉐보레',
    type: 'COMPACT',
  },
];

export const CONTRACTS = [
  {
    status: 'carInspection',
    contractPrice: 33098339,
    userId: 3,
    customerId: 1,
    carId: 1,
    companyId: 2,
  },
  {
    status: 'priceNegotiation',
    contractPrice: 20857019,
    userId: 4,
    customerId: 2,
    carId: 2,
    companyId: 2,
  },
  {
    status: 'contractDraft',
    contractPrice: 30080698,
    userId: 5,
    customerId: 3,
    carId: 3,
    companyId: 2,
  },
  {
    status: 'contractSuccessful',
    contractPrice: 0,
    userId: 6,
    customerId: 4,
    carId: 4,
    companyId: 2,
  },
  {
    status: 'contractFailed',
    contractPrice: 37397586,
    userId: 7,
    customerId: 5,
    carId: 5,
    companyId: 2,
  },
];

export const MEETINGS = [
  {
    date: '2025-09-22T09:30:00',
    alarms: ['2025-09-22T09:00:00', '2025-09-21T09:00:00'],
    contractId: 1,
  },
  {
    date: '2025-09-25T13:30:00',
    alarms: ['2025-09-25T09:00:00'],
    contractId: 1,
  },
  {
    date: '2025-09-21T12:30:00',
    alarms: [],
    contractId: 2,
  },
  {
    date: '2025-09-27T17:00:00',
    alarms: ['2025-09-26T09:00:00'],
    contractId: 4,
  },
];

export const CONTRACT_DOCUMENTS = [
  {
    fileName: 'contracts_example.jpeg',
  },
  {
    fileName: 'test_image.png',
  },
  {
    fileName: '계약서1.pdf',
  },
  {
    fileName: '계약서2.pdf',
  },
  {
    fileName: '관계없는계약서.pdf',
  },
  {
    fileName: '관계없는계약서2.pdf',
  },
];

export const CONTRACT_DOCUMENT_RELATIONS = [
  {
    contractId: 1,
    contractDocumentId: 1,
  },
  {
    contractId: 1,
    contractDocumentId: 2,
  },
  {
    contractId: 1,
    contractDocumentId: 3,
  },
  {
    contractId: 2,
    contractDocumentId: 4,
  },
];
